In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import japanize_matplotlib
import scipy
import sklearn
import math


In [12]:
np.array([[True, True, False, False, True, False, False],
       [False, False, False, False, False, True, True],
       [False, True, False, True, True, True, True]
       ])

array([[ True,  True, False, False,  True, False, False],
       [False, False, False, False, False,  True,  True],
       [False,  True, False,  True,  True,  True,  True]])

In [13]:
np.random.random([3, 7]) < 0.65

array([[False,  True,  True,  True, False,  True,  True],
       [False, False, False,  True, False,  True, False],
       [ True, False,  True,  True,  True, False,  True]])

In [14]:
(np.random.random([3, 7]) < 0.65).sum(axis=1) >= 4

array([ True,  True,  True])

In [15]:
n_trial = 1000000
n_battle = 7
win7 = ((np.random.random([n_trial, n_battle]) < 0.65).sum(axis = 1) >= int(n_battle / 2) + 1).sum()
win7 / n_trial

0.800167

In [16]:
n = 5
k = 3
math.factorial(n) / (math.factorial(k) * math.factorial(n - k))

10.0

In [17]:
def binomial_dist(k, n, p):
    """ 
    :param k: k
    :param n: n
    :param p: p
    :return : 二項分布
    """
    c = math.factorial(n) / (math.factorial(k) * math.factorial(n - k))
    return c * (p ** k) * ((1 - p) ** (n-k))

In [18]:
win7 = 0

for i in range(4, 8):
    win7 += binomial_dist(i, 7, 0.65)
    
win5 = 0
for i in range(3, 6):
    win5 += binomial_dist(i, 5, 0.65)
    
pd.DataFrame([[win7], [win5]], index=['七番勝負', '五番勝負'], columns=['勝率'])

勝率
七番勝負  0.800154
五番勝負  0.764831

In [20]:
from scipy.stats import binom

win7 = 0
for i in range(4, 8):
    win7 += binom.pmf(i, 7, 0.65)
    
win7

0.800154265625

In [25]:
def binomial_dist2(k, n, p):
    """ 
    二項分布(正規分布使用)
    :param k: k
    :param n: n
    :param p: p
    :return: 二項分布
    """
    x1 = 1
    x2 = np.sqrt(2* np.pi * n *p * (1-p))
    y1 = -1 * ((k-n*p) ** 2)
    y2 = 2 * n * p * (1 - p)
    return (x1 / x2) * np.exp(y1 / y2)

    
    

In [26]:
win7 = 0
for i in range(4, 8):
    win7 += binomial_dist2(i, 7, 0.65)

win5 = 0
for i in range(3, 6):
    win5 += binomial_dist2(i, 5, 0.65)
    
    
pd.DataFrame([[win7], [win5]], index=['七番勝負', '五番勝負'], columns=['勝率'])

勝率
七番勝負  0.795540
五番勝負  0.753376